/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import com.damaru.midimercury.Main;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        Main classUnderTest = new Main();
        
    }
}
